[global]
   interfaces = lo end0 # change as needed, see default interface w/ ip route | grep '^default'
   bind interfaces only = yes
   smb ports = 445
   security = user
   log file = /var/log/samba/%m.log
   max log size = 50
   printcap name = /dev/null
   load printers = no
   strict allocate = Yes
   allocation roundup size = 4096
   read raw = Yes
   server signing = No
   write raw = Yes
   strict locking = No
   socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072
   min receivefile size = 16384
   use sendfile = Yes
   aio read size = 16384
   aio write size = 16384
   wins support = yes
   server string = %h
   disable netbios = yes

[home]
   path = /home/ad
   guest ok = no
   comment = %h Home
   valid users = "@ad" "ad"
   force user = ad
   force group = ad
   read only = no
   browseable = yes
